### ISSUE TITLE
Add bootstrap to the react application

### ISSUE THREAD

**Issue by omprakashpeddamadthala** [omprakashpeddamadthala/expens-manager-frontend#4]
Add bootstrap library to react application.

- [x]  Install bootstrap 5 library to react
- [x] Redesign the ExpenseList cornponent
- [x] Commit the changes and push the code

**Comment by banjaminlee** [comment]
https://bold.pro/my/banjamin-lee-241212153841

This is my resume.
I want to work for you.
I look forward your reply.

**Comment by omprakashpeddamadthala** [comment]
Sure ,

Can share your resume pdf format

What is your skill set


________________________________
